RobertHeijn_Market/Web_Application/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Web_Application.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/Index.cshtml.cs
using Data;
using Logic.Classes.Accounts.Customer;
using Logic.Interfaces.Logic.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Application.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private ICustomerManager CustomerManager = new CustomerManager(new DBCustomerManager());

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RobertHeijn_Market/Web_Application/Pages/Info.cshtml.cs
using Data;
using Logic.Classes.Address;
using Logic.Classes.DeliveryOption.DeliveryOption;
using Logic.Classes.Orders;
using Logic.Enums;
using Logic.Interfaces.Logic.DeliveryOptions;
using Logic.Interfaces.Logic.Orders;
using Logic.Interfaces.Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Logic.Classes.DeliveryOption;
using Logic.Classes.DeliveryOption.TimeSlot;

namespace Web_Application.Pages
{
    public class InfoModel : PageModel
    {
        [BindProperty]
        public Address Address { get; set; }
        [BindProperty]
        public Order order { get; set; }
        [BindProperty]
        public List<Country> countries { get; set; }
        [BindProperty]
        public List<PaymentMethod> paymentMethods { get; set; }
        [BindProperty]
        public List<DeliveyOption> deliveyOptions { get; set; }
        [BindProperty]
        public List<Location>? Locations { get; set; }
        public int DeliveryOptionId { get; set; }
        public int CustomerID { get; set; }
        [BindProperty]
        public List<string> TimeSlots { get; set; }
        [BindProperty]
        public string ChosenDeliveryOption { get; set; }
        [BindProperty]
        public string check { get; set; }
        [BindProperty]
        public string? chosenDate { get; set; }
        [BindProperty]
        public Location? locationName { get; set; }

        private ICustomerAddressManager customerAddressManager = new AddressManager(new DBAdressManager());
        private ICustomerOrderManager customerOrderManager = new OrderManager(new DBOrderManager(), new DBCustomerManager());
        private IDeliveryOptionNameManager deliveryOptionNameManager = new DeliveryOptionNameManager(new DBDeliveryOptionNameManager());
        private ILocationManager locationManager = new LocationManager(new DBLocationManager());
        private ITimeSlotManager timeSlotManager = new TimeSlotManager(new DBTimeSlotManager(), new DBDeliveyOptionCharacteristics());

        public void OnGet()
        {
            try
            {
                CustomerID = HttpContext.Session.GetInt32("CustomerID").Value;
                countries = customerAddressManager.GetAllCountries();
                paymentMethods = customerOrderManager.GetPaymentMethods();
                deliveyOptions = deliveryOptionNameManager.GetDeliveryOptions();
                Locations = locationManager.GetAllLocations(DeliveryOptionId);
                if (DeliveryOptionId == 1)
                {
                    if (chosenDate != null)
                    {
                        DateOnly dateOnly = DateOnly.Parse(chosenDate);

                        TimeSlots = timeSlotManager.GetHomeAvailableTimeSlots(dateOnly, DeliveryOptionId);
                    }
                }
                else if (DeliveryOptionId == 2)
                {
                    if (locationName != null)
                    {
                        int locationId = locationManager.GetLocationId(locationName.ToString());

                        if (chosenDate != null)
                        {
                            DateOnly dateOnly = DateOnly.Parse(chosenDate);

                            timeSlotManager.GetPickUpAvailableTimeSlots(dateOnly, DeliveryOptionId, locationId);
                        }

                    }
                }
            }
            catch
            {
                Response.Redirect("/LogIn");

            }

        }

        public void OnPost()
        {
            CustomerID = HttpContext.Session.GetInt32("CustomerID").Value;

            Address address = new Address(0, Address.StreetName, Address.HouseNumber, Address.Postcode, Address.Country);
            customerAddressManager.AddAddressToCustomer(address, CustomerID);
            order = customerOrderManager.GetCart(CustomerID);


        }

        public void OnPostOrder()
        {
            HttpContext.Session.SetString("option", ChosenDeliveryOption);
            DeliveryOptionId = deliveryOptionNameManager.GetDeliveOptionId(ChosenDeliveryOption);

            check = HttpContext.Session.GetString("option");
            OnGet();
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/LogIn.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Data;
using Logic.Classes.Accounts.Customer;
using Logic.Interfaces.Logic.Customers;
using Logic.Classes.Accounts;

namespace Web_Application.Pages
{
    public class LogInModel : PageModel
    {
        [BindProperty]
        public Customer Customer { get; set; }
        public int CustomerID { get; set; }
        private ICustomerManager CustomerManager = new CustomerManager(new DBCustomerManager());

		public void OnPost()
        {
            if (CustomerManager.LogiIn(Customer.EmailAddress, Customer.Password))
            {
                CustomerID = CustomerManager.GetCustomerId(Customer.EmailAddress);

                HttpContext.Session.SetInt32("CustomerID", CustomerID);

                Response.Redirect("/Index");
            }
        }
	}
}

RobertHeijn_Market/Web_Application/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Application.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/Products.cshtml.cs
using Data;
using Logic.Classes;
using Logic.Classes.Accounts.Customer;
using Logic.Classes.Orders;
using Logic.Classes.ProductOrder;
using Logic.Classes.Products;
using Logic.Interfaces.Data;
using Logic.Interfaces.Logic;
using Logic.Interfaces.Logic.Customers;
using Logic.Interfaces.Logic.Orders;
using Logic.Interfaces.Logic.Products;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Web_Application.Pages.Shared;

namespace Web_Application.Pages
{
    public class ProductsModel : PageModel
    {
        [BindProperty]
        public List<Product> products { get; set; }
        [BindProperty]
        public double productNewPrice { get; set; }
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public int productId { get; set; }
        [BindProperty]
        public int CustomerID { get; set; }

        private ICustomerProductManager customerProductManager = new ProductManager(new DBProductManager());
        private ICustomerManager customerManager = new CustomerManager(new DBCustomerManager());
        private ICustomerOrderManager customerOrderManager = new OrderManager(new DBOrderManager(), new DBCustomerManager());
        private IProductOrderManager productOrderManager = new ProductOrderManager(new DBProductOrderManage());

        public void OnGet()
        {
            products = customerProductManager.GetProducts();
        }

        public void OnPost()
        {
            try
            {
                CustomerID = HttpContext.Session.GetInt32("CustomerID").Value;

                if (customerOrderManager.GetCart(CustomerID) != null)
                {
                    Order order = customerOrderManager.GetCart(CustomerID);
                    Product product = customerProductManager.GetProductByID(productId);

                    if (productOrderManager.GetProductOrder(order.Id, productId) != null)
                    {
                        ProductOrder productOrder = productOrderManager.GetProductOrder(order.Id, productId);

                        if (productOrder.Product.Id == productId)
                        {
                            productOrder.Quantity = Quantity;
                            productOrder.Price = productNewPrice;

                            productOrderManager.EditProductOrder(productOrder, order.Id);

                            OnGet();

                            return;
                        }
                    }
                    else
                    {
                        ProductOrder productOrder2 = new ProductOrder(product, Quantity, productNewPrice);
                        order.ProductOrder.Add(productOrder2);

                        productOrderManager.AddProductToOrder(productOrder2, order.Id);

                        OnGet();

                        return;
                    }
                }
                else
                {
                    DateTime thisDay = DateTime.Today;

                    Product product = customerProductManager.GetProductByID(productId);

                    ProductOrder productOrder = new ProductOrder(product, Quantity, productNewPrice);
                    List<ProductOrder> productOrders = new List<ProductOrder>();
                    productOrders.Add(productOrder);

                    Order order = new Order(0, thisDay.ToString(), productOrders);

                    customerOrderManager.CreateCart(order, CustomerID);

                    int cartId = customerOrderManager.GetCartId(CustomerID);
                    productOrderManager.AddProductToOrder(productOrder, cartId);

                    OnGet();

                    return;
                }
            }
            catch
            {
                Response.Redirect("/LogIn");
            }
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/ShoppingCart.cshtml.cs
using Data;
using Logic.Classes.Accounts.Customer;
using Logic.Classes.Orders;
using Logic.Classes.ProductOrder;
using Logic.Classes.Products;
using Logic.Interfaces.Logic;
using Logic.Interfaces.Logic.Orders;
using Logic.Interfaces.Logic.Products;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Application.Pages
{
    public class ShoppingCartModel : PageModel
    {
        [BindProperty]
        public List<ProductOrder> productOrders { get; set; }
        public int CustomerID { get; set; }
        [BindProperty]
        public int ProductId { get; set; }
        [BindProperty]
        public double OrderTotalPrice { get; set; }

        private ICustomerOrderManager customerOrderManager = new OrderManager(new DBOrderManager(), new DBCustomerManager());
        private ICustomerProductManager customerProductManager = new ProductManager(new DBProductManager());
        private IProductOrderManager productOrderManager = new ProductOrderManager(new DBProductOrderManage());

        public void OnGet()
        {
            try
            {
                CustomerID = HttpContext.Session.GetInt32("CustomerID").Value;
                Order cart = customerOrderManager.GetCart(CustomerID);
                productOrders = cart.ProductOrder;

                OrderTotalPrice = productOrderManager.CalculateOrderTotalPrice(cart.Id);
                cart.TotalOrderPrice = OrderTotalPrice;
                customerOrderManager.AddOrderTotalPrice(cart);
            }
            catch
            {
                Response.Redirect("/LogIn");
            }
        }

        public void OnPostDeleteProduct()
        {
            CustomerID = HttpContext.Session.GetInt32("CustomerID").Value;
            int cartId = customerOrderManager.GetCartId(CustomerID);
            productOrderManager.RemoveProduct(ProductId, cartId);
            OnGet();
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/SignUp.cshtml.cs
using Data;
using Logic.Classes.Accounts.Customer;
using Logic.Interfaces.Logic.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web_Application.Pages
{
    public class SignUpModel : PageModel
    {
        [BindProperty]
        public Customer Customer { get; set; }
        public string Message { get; set; }
        private ICustomerManager CustomerManager;

        public void OnPost()
        {
            CustomerManager = new CustomerManager(new DBCustomerManager());

            if (CustomerManager.SignUp(Customer))
            {
                Response.Redirect("/LogIn");
            }
            else
            {
                Message = $"There is already an account with this emailaddress:{Customer.EmailAddress} !";

                Customer.Name = "";
                Customer.LastName = "";
                Customer.EmailAddress = "";
                Customer.PhoneNumber = 0;
            }
        }
    }
}

RobertHeijn_Market/Web_Application/Pages/Info.cshtml
@page
@model Web_Application.Pages.InfoModel
@{
}

<section class="u-align-center u-clearfix u-grey-5 u-section-1">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-form u-form-1">
            @*<form method="post" class="u-clearfix u-form-spacing-20 u-form-vertical u-inner-form" style="padding: 10px">*@
            <div class="u-form-group u-form-select u-label-top u-form-group-5">
                <label class="u-label">Country</label>
                <div class="u-form-select-wrapper">
                    <select asp-for="Address.Country" class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-5" required="required">
                        <option value="" selected disabled>Select your country</option>
                        @foreach (var country in Model.countries)
                        {
                            <option value="counrty">@country</option>
                        }
                    </select>
                    <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
                </div>
            </div>
            <div class="u-form-group u-label-top u-form-group-7">
                <label class="u-label">Postcode</label>
                <input type="text" placeholder="enter your postcode" asp-for="Address.Postcode" class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-7" required="required">
            </div>
            <div class="u-form-group u-label-top u-form-group-9">
                <label class="u-label">House Number</label>
                <input type="text" placeholder="enter you House Number" asp-for="Address.HouseNumber" class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-9">
            </div>
            <div class="u-form-group u-label-top u-form-group-10">
                <label class="u-label">Street Name</label>
                <input type="text" placeholder="enter your Street Name" asp-for="Address.StreetName" class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-10" required="required">
            </div>
            <div class="u-form-group u-form-select u-label-top u-form-group-1">
                <label for="select-90bf" class="u-label">Choose a payment method</label>
                <div class="u-form-select-wrapper">
                    <select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-1" required="required" asp-for="order.PaymentMethod">
                        @foreach (var paymentMethod in Model.paymentMethods)
                        {
                            <option value="paymentMethod">@paymentMethod</option>
                        }
                    </select>
                    <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
                </div>
            </div>


            @*</form>*@

            @*   @if (Model.check != null)
            {
            <select name="number">
            <option value="">Select a number</option>
            @foreach (var s in Model.timsolts)
            {
            if (s.deliveryType == Model.check)
            {
            <option value="@s.deliveryTime">@s.deliveryTime</option>

            }
            }
            </select>
            }*@
            <form method="post" asp-page-handler="order">
                <select asp-for="@Model.ChosenDeliveryOption">
                    <option value="">Select a delivery option</option>
                    @foreach (var option in Model.deliveyOptions)
                    {
                        <option value="@option.Name">@option.Name</option>
                    }
                </select>
                <div class="u-form-date u-form-group u-label-top u-form-group-3">
                    <label for="date-345a" class="u-label">Choose a date</label>
                    <input type="date" placeholder="MM/DD/YYYY" class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-3" required="required" asp-for="@Model.chosenDate">
                </div>

                @if (Model.check == "PickUp")
                {
                    <select asp-for="@Model.locationName">
                        <option value="">Choose your location</option>
                        @foreach (var location in @Model.Locations)
                        {
                            <option value="@location">@location</option>
                        }
                    </select>
                    @if (Model.locationName != null)
                    {
                        <select>
                            <option value="">Choose your timeslot</option>
                            @foreach (var timeslot in Model.TimeSlots)
                            {
                                <option value="@timeslot">@timeslot</option>
                            }
                        </select>
                    }
                }
                else if (Model.check == "Home")
                {
                    <select>
                        @foreach (var timeslot in Model.TimeSlots)
                        {
                            <option value="@timeslot">@timeslot</option>
                        }
                    </select>
                }

                <button type="submit">submit</button>
            </form>
            @*    <div class="u-form-group u-form-select u-label-top u-form-group-2">
            <label class="u-label">Choose a delivery option</label>
            <div class="u-form-select-wrapper">*@
            @* @functions {
            public string GetDeliveryOption(String deliveryOption)
            {
            InfoModel infoModel = new InfoModel();
            infoModel.OnDeliveryOptionClick(deliveryOption);
            return deliveryOption;
            }
            }*@@*nclick="OnOptionClick(this)"*@

            @*<select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-2" required="required">

            <option selected disabled>Select your delivery option</option>
            @foreach (var deliveryOption in Model.deliveyOptions)
            {
            <option value="@deliveryOption.Name">
            @deliveryOption.Name
            </option>
            }

            </select>
            <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>*@
            @*</div>
            </div>*@
            @*                <button type="submit" class="u-border-2 u-border-grey-75 u-btn u-btn-submit u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">NEXT</button>
            *@                @*
            @@*if (Model.DeliveryOptionName == "PickUp")
            {*@
            @*<div  class="u-form-group u-form-select u-label-top u-form-group-2">
            <label class="u-label">Choose a location</label>
            <div class="u-form-select-wrapper">*@
            @*@functions {
            public List<string> GetLocations()
            {
            InfoModel infoModel = new InfoModel();
            return infoModel.DisplayLocations(location);
            }
            }*@@*onclick="OnOptionClick(this)"*@

            @*<select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-2" required="required">
            @foreach (var location in Model.Locations)
            {
            <option value="location">@location</option>
            }
            </select>
            <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
            @*  </div>*@
            @*                </div>*@
            @*}*@


            @*    <div id="time_slots" style="display: none;" class="u-form-group u-form-select u-label-top u-form-group-2">
            <label class="u-label">Choose a Time Slot</label>
            <div class="u-form-select-wrapper">
            <select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-2" required="required">

            <option value="location">HI</option>

            </select>
            <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
            </div>
            </div>




            @*<div class="u-form-group u-form-select u-label-top u-form-group-4">
            <div class="u-form-group u-form-select u-label-top u-form-group-4">
            <select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-4">
            <label class="u-label">Choose a timeslot</label>
            @if (Model.deliveryOption == "Home delivery")
            {
            <option value="Item 1">Item 1</option>
            }
            </select>
            <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
            </div>
            </div>
            <div class="u-form-group u-form-select u-label-top u-form-group-5">
            <label class="u-label">Choose a location</label>
            <div class="u-form-select-wrapper">
            <select class="u-border-2 u-border-black u-border-no-left u-border-no-right u-border-no-top u-input u-input-rectangle u-input-5">
            <option value="Item 1">Item 1</option>
            <option value="Item 2">Item 2</option>
            <option value="Item 3">Item 3</option>
            </select>
            <svg class="u-caret u-caret-svg" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="16px" height="16px" viewBox="0 0 16 16" style="fill:currentColor;" xml:space="preserve"><polygon class="st0" points="8,12 2,4 14,4 "></polygon></svg>
            </div>
            </div>*@
            <div class="u-align-center u-form-group u-form-submit u-label-top">
                @*  <button type="submit" class="u-border-2 u-border-grey-75 u-btn u-btn-submit u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">
                Order<br>
                </button>*@
            </div>
        </div>
    </div>
</section>

@*//let test = "";
        //function OnOptionClick(item, event, cli) {
        //    console.log('test');
        //    console.log(item, item.value, cli);
        //    if (item.value == "PickUp") {
        //        document.getElementById("loction_options").style.display = "block";
        //        document.getElementById("time_slots").style.display = "none";
        //    } else if (item.value == "Home") {*@
@* //        document.getElementById("loction_options").style.display = "none";
        //        document.getElementById("time_slots").style.display = "block";
        //    }*@
@*     //@GetDeliveryOption("PickUp")
        //                } function OnLocationClick(item, event, cli) {
        //    console.log('test');
        //    console.log(item, item.value, cli);
        //    document.getElementById("time_slots").style.display = "block";

        //@GetDeliveryOption("PickUp")*@

RobertHeijn_Market/Web_Application/Pages/LogIn.cshtml
@page
@model Web_Application.Pages.LogInModel
@{
}
<link rel="stylesheet" href="~/css/login.css">
<section class="u-align-center u-clearfix u-section-1" id="sec-797f">
    <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-default u-text-1">
            Login<span class="u-text-custom-color-1"></span>
        </h2>
        <div class="u-form u-form-1">
            <form method="post" class="u-clearfix u-form-spacing-15 u-inner-form" style="padding: 15px;" source="email">
                <div class="u-form-group u-form-name u-label-none">
                    <label for="name-ef64" class="u-label">input</label>
                    <input type="text" placeholder="Email " asp-for="Customer.EmailAddress" class="u-border-1 u-border-grey-30 u-input u-input-rectangle" required="required">
                </div>
                <div class="u-form-group u-label-none">
                    <label for="email-ef64" class="u-label">input</label>
                    <input type="password" placeholder="Password" asp-for="Customer.Password" class="u-border-1 u-border-grey-30 u-input u-input-rectangle" required="required">
                </div>
                <div class="u-form-group u-form-submit">
                    <a href="#" class="u-border-2 u-border-grey-75 u-btn u-btn-submit u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-1" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction="">LOGIN</a>
                    <input type="submit" value="submit" class="u-form-control-hidden">
                </div>
            </form>
        </div>
    </div>
</section>

RobertHeijn_Market/Web_Application/Pages/Products.cshtml
@page
@model Web_Application.Pages.ProductsModel
@{
}

<link rel="stylesheet" href="~/css/products.css">

<section class="u-align-center u-clearfix u-section-1">
    <div class="u-clearfix u-sheet u-sheet-1">
        @foreach (var product in Model.products)
        {
            <form method="post">
                <input type="hidden" value="@product.Id" asp-for="@Model.productId">
                <input type="hidden" value="@product.Price" asp-for="productNewPrice">

                <img src="@product.Image"><img />
                <p class="u-text u-text-default u-text-1">@product.Name</p>
                <p class="u-text u-text-default u-text-2">@product.Price €</p>
                <div class="u-form-select-wrapper">
                    <select class="u-border-1 u-border-grey-30 u-input u-input-rectangle" asp-for="@Model.Quantity">
                        @for (int Quantity = 1; Quantity <= product.CurrentAmount; Quantity++)
                        {
                            <option value="@Quantity">@Quantity</option>
                        }
                    </select>
                </div>
                <button type="submit" class="u-border-2 u-border-grey-75 u-btn u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-1">Add to cart</button>
            </form>
        }
    </div>
        <a asp-page="/ShoppingCart" class="u-border-2 u-border-grey-75 u-btn u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-1">Checkout</a>
</section>

RobertHeijn_Market/Web_Application/Pages/ShoppingCart.cshtml
@page
@model Web_Application.Pages.ShoppingCartModel
@{
}
<section class="u-clearfix u-section-1">
    <div class="u-clearfix u-sheet u-sheet-1">
        @foreach (var productOrder in Model.productOrders)
        {
            <form method="post">
                <img src="@productOrder.Product.Image">

                <img />
                <p class="u-text u-text-default u-text-1">@productOrder.Product.Name</p>
                <p class="u-text u-text-default u-text-2">@productOrder.Quantity</p>
                <p class="u-text u-text-default u-text-2">@productOrder.Price €</p>
                <input type="hidden" value="@productOrder.Product.Id" asp-for="ProductId">
                <button type="submit" asp-page-handler="DeleteProduct" class="u-border-2 u-border-grey-75 u-btn u-button-style u-custom-color-2 u-hover-palette-1-dark-1 u-btn-1">Delete</button>
            </form>
        }
        <p class="u-text u-text-default u-text-3">@Model.OrderTotalPrice €</p>
        <a href="/Info" class="u-border-2 u-border-grey-75 u-btn u-button-style u-custom-color-1 u-hover-palette-1-dark-1 u-btn-2">Confirm</a>
    </div>
</section>